CREATE TABLE PRODUTOS(
	CODIGO			INT			NOT NULL,
	DESCRICAO		VARCHAR(50) NOT NULL,
	DATA_VALIDADE	DATETIME,
	EAN				VARCHAR(15) NOT NULL,
	IND_INATIVO		INT			NOT NULL	DEFAULT 0,
);

ALTER TABLE PRODUTOS 
	ADD CONSTRAINT PK_PRODUTOS  
		PRIMARY KEY (CODIGO);

CREATE INDEX IDX_PRODUTOS_EAN
	ON PRODUTOS(EAN);

INSERT INTO PRODUTOS VALUES(1, 'Pastel de flango, né !', GETDATE(), '0123456789', 0);

INSERT INTO PRODUTOS(CODIGO, DESCRICAO, EAN) VALUES(2, 'Pastel de CARNE, né !','5555555555');

SELECT * FROM PRODUTOS;

SELECT COUNT(*)
	FROM PRODUTOS;



CREATE TABLE LOJA(
	CODIGO			INT				NOT NULL,
	NOME			VARCHAR(50)		NOT NULL,
	IND_INATIVO		INT				NOT NULL	DEFAULT 0
	CONSTRAINT LOJA_PK PRIMARY KEY (CODIGO)
);


INSERT INTO LOJA(CODIGO, NOME) VALUES(1000, 'Filial Nova SC/SE');
INSERT INTO LOJA(CODIGO, NOME) VALUES(1001, 'Filial Nova SO/SE');
INSERT INTO LOJA(CODIGO, NOME) VALUES(1002, 'Filial Nova AJ/SE');
INSERT INTO LOJA(CODIGO, NOME) VALUES(1003, 'Filial Nova IT/SE');

SELECT * FROM LOJA;

SELECT CODIGO, 
		NOME
	FROM LOJA 
WHERE IND_INATIVO = 0;


CREATE TABLE ESTOQUE(
	CODIGO_PRODUTO		INT			NOT NULL,
	CODIGO_FILIAL		INT			NOT NULL,
	QUANTIDADE			DECIMAL		NOT NULL  DEFAULT 0
	CONSTRAINT ESTOQUE_PK PRIMARY KEY(CODIGO_PRODUTO, CODIGO_FILIAL)
);

INSERT INTO ESTOQUE(CODIGO_PRODUTO, CODIGO_FILIAL, QUANTIDADE) VALUES(1, 10, 1);

SELECT * FROM ESTOQUE;

DELETE FROM ESTOQUE;

ALTER TABLE ESTOQUE
	ADD CONSTRAINT FK_ESTOQUE_PRODUTOS
		FOREIGN KEY (CODIGO_PRODUTO)
		REFERENCES PRODUTOS(CODIGO);

ALTER TABLE ESTOQUE
	ADD CONSTRAINT FK_ESTOQUE_LOJAS
		FOREIGN KEY (CODIGO_PRODUTO)
		REFERENCES PRODUTOS(CODIGO);